/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/components/About.vue')['default']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACol: typeof import('ant-design-vue/es')['Col']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADatePicker: typeof import('ant-design-vue/es')['DatePicker']
    AFlex: typeof import('ant-design-vue/es')['Flex']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AImage: typeof import('ant-design-vue/es')['Image']
    AInput: typeof import('ant-design-vue/es')['Input']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ATypographyLink: typeof import('ant-design-vue/es')['TypographyLink']
    ATypographyTitle: typeof import('ant-design-vue/es')['TypographyTitle']
    BlockTitle: typeof import('./src/components/BlockTitle.vue')['default']
    Blog: typeof import('./src/components/Blog.vue')['default']
    Contacts: typeof import('./src/components/Contacts.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Gallery: typeof import('./src/components/Gallery.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    PageTemplate: typeof import('./src/components/PageTemplate.vue')['default']
    PopularRoutes: typeof import('./src/components/PopularRoutes.vue')['default']
    Preview: typeof import('./src/components/Preview.vue')['default']
    PreviewForm: typeof import('./src/components/PreviewForm.vue')['default']
    Programs: typeof import('./src/components/Programs.vue')['default']
  }
}
