/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADatePicker: typeof import('ant-design-vue/es')['DatePicker']
    AFlex: typeof import('ant-design-vue/es')['Flex']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ATypographyLink: typeof import('ant-design-vue/es')['TypographyLink']
    ATypographyTitle: typeof import('ant-design-vue/es')['TypographyTitle']
    Header: typeof import('./src/components/Header.vue')['default']
    Preview: typeof import('./src/components/Preview.vue')['default']
    PreviewForm: typeof import('./src/components/PreviewForm.vue')['default']
  }
}
